Create workflows
ictsc/ictsc-sachiko-v3 pull request #87
Opened 2023-01-09 16:18 UTC by Crow314

mainブランチへのpush時にコンテナイメージをビルドし、ghcr.ioへプッシュするGitHub Actions Workflowの作成

2023-01-09 16:42 UTC, x86taka requested changes

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/mgmt-push-sakura-registry.yaml
> +          #   next_public_answer_limit=
20に設定して欲しいです！

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/push-sakura-registry.yaml
> +          #   next_public_answer_limit=
同様に20にして欲しいです！

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/dev-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.dev.ictsc.net
/apiが必要です!
```suggestion
            next_public_api_url=https://scoreserver.dev.ictsc.net/api
```

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/dev-push-sakura-registry.yaml
> +          #   next_public_answer_limit=
20にして欲しいです！

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/mgmt-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.mgmt.ictsc.net
```suggestion
            next_public_api_url=https://contest.mgmt.ictsc.net/api
```

2023-01-09 16:42 UTC, x86taka commented on .github/workflows/push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.ictsc.net
```suggestion
            next_public_api_url=https://contest.ictsc.net/api
```

2023-01-09 17:32 UTC, Crow314 commented on .github/workflows/dev-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.dev.ictsc.net
ここはドメイン `scoreserver.dev.ictsc.net` で大丈夫です？

2023-01-09 17:56 UTC, x86taka commented on .github/workflows/dev-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.dev.ictsc.net
~~contest.devにしてもらった方がいいかもしれないです。~~

そもそもdev環境をこちら側(k8s)で用意するか決まっていないので、 @K-shir0 に聞いてからにしたいと思います。 👀

2023-01-09 21:16 UTC, K-shir0 commented on .github/workflows/dev-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.dev.ictsc.net
@x86taka @Crow314 
できる限り本番に近づけて運用した方が良いと考えているのでインフラ側の負担にならなければ用意したいです。

2023-01-10 09:07 UTC, x86taka commented on .github/workflows/dev-push-sakura-registry.yaml
> +            next_public_api_url=https://scoreserver.dev.ictsc.net
@Crow314 
devを用意することを想定して`contest.dev.`でお願いします！

2023-01-12 19:27 UTC, x86taka approved these changes

2023-01-12 19:28 UTC, merged